@TmsApi_HostAddress = http://localhost:5001

GET {{TmsApi_HostAddress}}/weatherforecast/
Accept: application/json

###

# api/assessments/results"
GET {{TmsApi_HostAddress}}/api/assessments/results
Accept: application/json
